### ISSUE TITLE
Readme.md description is not clear  

### ISSUE THREAD

**Issue by Yionse** [Azure-Samples/eShopLite-SemanticSearch#2]
**Description:**
The readme does not clearly describe where to add the code in the figure below.
![image](https://github.com/user-attachments/assets/64944afe-96f6-41b4-830a-0f1993aace01)
 
**Suggestion:**
Change the above code to the following command:
```
cd src/Products
dotnet user-secrets set "ConnectionStrings:openaidev" "Endpoint=https://<endpoint>.openai.azure.com/;Key=<key>;"
```
 
@elbruno, @PabloNunes and @hemarina for notification.

**Comment by elbruno** [comment]
> **Description:** The readme does not clearly describe where to add the code in the figure below. ![image](https://private-user-images.githubusercontent.com/111940661/392723791-64944afe-96f6-41b4-830a-0f1993aace01.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1Mjg0ODcsIm5iZiI6MTczMzUyODE4NywicGF0aCI6Ii8xMTE5NDA2NjEvMzkyNzIzNzkxLTY0OTQ0YWZlLTk2ZjYtNDFiNC04MzBhLTBmMTk5M2FhY2UwMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNlQyMzM2MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mM2YwNDVmNGNkZGY4MDI2YjYzYmJjOGRjZTZkNWU2ZDlmYThmNjE0YmIwMjg2MTI5OTQxOGMzZTcwZjM5MTIwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.N2tf6DyWACovu14wDeh5GtFgYMASaVQeQzXI5W_m2bY)
> 
> **Suggestion:** Change the above code to the following command:
> 
> ```
> cd src/Products
> dotnet user-secrets set "ConnectionStrings:openaidev" "Endpoint=https://<endpoint>.openai.azure.com/;Key=<key>;"
> ```
> 
> @elbruno, @PabloNunes and @hemarina for notification.

Thanks for the feedback @Yionse , added the suggestion in the main Readme.
